### PR TITLE
Variable fix

### PR DESCRIPTION
**Pull request by GettingTechnicl**

### CODE REVIEW

**Comment by mlan** [comment]
Hello @GettingTechnicl on which platform did you experience issues with variables?

BTW: amavis is getting difficult to support, so I'm about to retire this image. I suggest you checkout these instead:
[mlan/postfix](https://github.com/mlan/docker-postfix)
[mlan/rspamd](https://github.com/mlan/docker-rspamd)

**Comment by GettingTechnicl** [comment]
I am currently looking in to your postfix package.

The variables I updated were those specified in the docker-compose.yml
within the demo folder. The variables are such as
"MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-secret}", whereas in the
corresponding .env the variable is MYSQL_ROOT_PASSWORD, therefore proper
syntax in the docker-compose.yml would be
"MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"


I believe to have a decent understanding of dockers and environment
variable files. I am currently converting an existing mail config I had
utilizing postfix/dovecot/mysql without migrating data. I don't recall the
variables specifically to get everything running through my relay properly,
however once I get this set up it will certainly help to make the email
server setup more transparent and manageable moving forward.

**Comment by mlan** [comment]
Hi @GettingTechnicl that sounds like an interesting project.

Please have a look at [Environment variables in Compose](https://docs.docker.com/compose/environment-variables/) to see how default values can be used.

**Comment by GettingTechnicl** [comment]
This confirms the reasoning for the fixes on the yml

**Comment by mlan** [comment]
@GettingTechnicl for this issue to advance you need to clearly state what problem is that you are experiencing.

**Comment by mlan** [comment]
Maintance of this repo is discontinued.

**Pull request closed without merging**
